name: local_recipe_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2-97.0.dev

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: any
  geolocator: ^11.0.0
  http: ^0.13.6
  provider: ^6.0.5
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
